// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Seatgenie.Api.Data;

#nullable disable

namespace Seatgenie.Api.Migrations
{
    [DbContext(typeof(SeatGenieDbContext))]
    [Migration("20260703123156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Seatgenie.Api.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<int?>("ExpiresAt")
                        .HasColumnType("integer")
                        .HasColumnName("expires_at");

                    b.Property<int?>("ExtExpiresIn")
                        .HasColumnType("integer")
                        .HasColumnName("ext_expires_in");

                    b.Property<string>("IdToken")
                        .HasColumnType("text")
                        .HasColumnName("id_token");

                    b.Property<string>("Provider")
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .HasColumnType("text")
                        .HasColumnName("provider_account_id");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SessionState")
                        .HasColumnType("text")
                        .HasColumnName("session_state");

                    b.Property<string>("TokenType")
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_account");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_account_user_id");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique()
                        .HasDatabaseName("i_x_account_provider_provider_account_id");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Desk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FloorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("floor_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicDeskId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_desk_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("p_k_desk");

                    b.HasIndex("FloorId", "PublicDeskId")
                        .IsUnique()
                        .HasDatabaseName("i_x_desk_floor_id_public_desk_id");

                    b.ToTable("desk", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.DeskRecommendation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("DeskId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desk_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<double>("Score")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_desk_recommendation");

                    b.HasIndex("DeskId")
                        .HasDatabaseName("i_x_desk_recommendation_desk_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_desk_recommendation_user_id");

                    b.ToTable("desk_recommendation", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.DeskSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("DeskId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desk_id");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Etc/GMT")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<bool>("WholeDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("whole_day");

                    b.HasKey("Id")
                        .HasName("p_k_desk_schedule");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_desk_schedule_user_id");

                    b.HasIndex("DeskId", "Date")
                        .HasDatabaseName("i_x_desk_schedule_desk_id_date");

                    b.ToTable("desk_schedule", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Floor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FloorPlan")
                        .HasColumnType("text")
                        .HasColumnName("floor_plan");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OfficeId")
                        .HasColumnType("text")
                        .HasColumnName("office_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_floor");

                    b.HasIndex("OfficeId")
                        .HasDatabaseName("i_x_floor_office_id");

                    b.ToTable("floor", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.MeetingRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FloorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("floor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_meeting_room");

                    b.HasIndex("FloorId")
                        .HasDatabaseName("i_x_meeting_room_floor_id");

                    b.ToTable("meeting_room", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Office", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OfficeSettingId")
                        .HasColumnType("text")
                        .HasColumnName("office_setting_id");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Etc/GMT")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_office");

                    b.HasIndex("OfficeSettingId")
                        .HasDatabaseName("i_x_office_office_setting_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_office_organization_id");

                    b.ToTable("office", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.OfficeRoom", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FloorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("floor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_office_room");

                    b.HasIndex("FloorId")
                        .HasDatabaseName("i_x_office_room_floor_id");

                    b.ToTable("office_room", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.OfficeSetting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("AllowSchedulingInThePast")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_scheduling_in_the_past");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationSchedulingFuture")
                        .HasColumnType("integer")
                        .HasColumnName("duration_scheduling_future");

                    b.Property<string>("OfficeSettingWeekdaysAllowedId")
                        .HasColumnType("text")
                        .HasColumnName("office_setting_weekdays_allowed_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_office_setting");

                    b.HasIndex("OfficeSettingWeekdaysAllowedId")
                        .HasDatabaseName("i_x_office_setting_office_setting_weekdays_allowed_id");

                    b.ToTable("office_setting", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.OfficeSettingWeekdaysAllowed", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("AllowFriday")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_friday");

                    b.Property<bool>("AllowMonday")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_monday");

                    b.Property<bool>("AllowSaturday")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_saturday");

                    b.Property<bool>("AllowSunday")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_sunday");

                    b.Property<bool>("AllowThursday")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_thursday");

                    b.Property<bool>("AllowTuesday")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_tuesday");

                    b.Property<bool>("AllowWednesday")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_wednesday");

                    b.HasKey("Id")
                        .HasName("p_k_office_setting_weekdays_allowed");

                    b.ToTable("office_setting_weekdays_allowed", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.OnboardingSelection", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Submitted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("submitted");

                    b.Property<string>("TemporaryInviteCode")
                        .HasColumnType("text")
                        .HasColumnName("temporary_invite_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.PrimitiveCollection<List<string>>("WorkplacifyPreferences")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("workplacify_preferences");

                    b.HasKey("Id")
                        .HasName("p_k_onboarding_selection");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_onboarding_selection_user_id");

                    b.ToTable("onboarding_selection", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organization");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_organization_invite_code");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("session_token");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_session");

                    b.HasIndex("SessionToken")
                        .IsUnique()
                        .HasDatabaseName("i_x_session_session_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_session_user_id");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CurrentOfficeId")
                        .HasColumnType("text")
                        .HasColumnName("current_office_id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text")
                        .HasColumnName("organization_id");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_role");

                    b.HasKey("Id")
                        .HasName("p_k_user");

                    b.HasIndex("CurrentOfficeId")
                        .HasDatabaseName("i_x_user_current_office_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_user_organization_id");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.UserPreference", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FavoriteDeskId")
                        .HasColumnType("text")
                        .HasColumnName("favorite_desk_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<bool>("PreferFriday")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_friday");

                    b.Property<bool>("PreferMonday")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_monday");

                    b.Property<bool>("PreferSaturday")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_saturday");

                    b.Property<bool>("PreferSunday")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_sunday");

                    b.Property<bool>("PreferThursday")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_thursday");

                    b.Property<bool>("PreferTuesday")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_tuesday");

                    b.Property<bool>("PreferWednesday")
                        .HasColumnType("boolean")
                        .HasColumnName("prefer_wednesday");

                    b.Property<string>("PreferredFloorId")
                        .HasColumnType("text")
                        .HasColumnName("preferred_floor_id");

                    b.Property<string>("PreferredOfficeId")
                        .HasColumnType("text")
                        .HasColumnName("preferred_office_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_preference");

                    b.HasIndex("FavoriteDeskId")
                        .HasDatabaseName("i_x_user_preference_favorite_desk_id");

                    b.HasIndex("PreferredFloorId")
                        .HasDatabaseName("i_x_user_preference_preferred_floor_id");

                    b.HasIndex("PreferredOfficeId")
                        .HasDatabaseName("i_x_user_preference_preferred_office_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_preference_user_id");

                    b.ToTable("user_preference", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.VerificationToken", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.HasKey("Identifier", "Token")
                        .HasName("p_k_verification_token");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("i_x_verification_token_token");

                    b.ToTable("verification_token", (string)null);
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Account", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_account_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Desk", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.Floor", "Floor")
                        .WithMany("Desks")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_desk_floor_floor_id");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.DeskRecommendation", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.Desk", "Desk")
                        .WithMany("DeskRecommendations")
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_desk_recommendation_desk_desk_id");

                    b.HasOne("Seatgenie.Api.Entities.User", "User")
                        .WithMany("DeskRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_desk_recommendation_user_user_id");

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.DeskSchedule", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.Desk", "Desk")
                        .WithMany("DeskSchedules")
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_desk_schedule_desk_desk_id");

                    b.HasOne("Seatgenie.Api.Entities.User", "User")
                        .WithMany("DeskSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_desk_schedule_user_user_id");

                    b.Navigation("Desk");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Floor", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.Office", "Office")
                        .WithMany("Floors")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_floor_office_office_id");

                    b.Navigation("Office");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.MeetingRoom", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.Floor", "Floor")
                        .WithMany("MeetingRooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_meeting_room_floor_floor_id");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Office", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.OfficeSetting", "OfficeSetting")
                        .WithMany("Offices")
                        .HasForeignKey("OfficeSettingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_office_office_setting_office_setting_id");

                    b.HasOne("Seatgenie.Api.Entities.Organization", "Organization")
                        .WithMany("Offices")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_office_organization_organization_id");

                    b.Navigation("OfficeSetting");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.OfficeRoom", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.Floor", "Floor")
                        .WithMany("OfficeRooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_office_room_floor_floor_id");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.OfficeSetting", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.OfficeSettingWeekdaysAllowed", "WeekdaysAllowed")
                        .WithMany()
                        .HasForeignKey("OfficeSettingWeekdaysAllowedId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_office_setting_office_setting_weekdays_allowed_office_setti~");

                    b.Navigation("WeekdaysAllowed");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.OnboardingSelection", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.User", "User")
                        .WithOne("OnboardingSelection")
                        .HasForeignKey("Seatgenie.Api.Entities.OnboardingSelection", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_onboarding_selection_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Session", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_session_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.User", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.Office", "CurrentOffice")
                        .WithMany()
                        .HasForeignKey("CurrentOfficeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_user_office_current_office_id");

                    b.HasOne("Seatgenie.Api.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_k_user_organization_organization_id");

                    b.Navigation("CurrentOffice");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.UserPreference", b =>
                {
                    b.HasOne("Seatgenie.Api.Entities.Desk", "FavoriteDesk")
                        .WithMany()
                        .HasForeignKey("FavoriteDeskId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_user_preference_desk_favorite_desk_id");

                    b.HasOne("Seatgenie.Api.Entities.Floor", "PreferredFloor")
                        .WithMany()
                        .HasForeignKey("PreferredFloorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_user_preference_floor_preferred_floor_id");

                    b.HasOne("Seatgenie.Api.Entities.Office", "PreferredOffice")
                        .WithMany()
                        .HasForeignKey("PreferredOfficeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_user_preference_office_preferred_office_id");

                    b.HasOne("Seatgenie.Api.Entities.User", "User")
                        .WithOne("UserPreference")
                        .HasForeignKey("Seatgenie.Api.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_preference_user_user_id");

                    b.Navigation("FavoriteDesk");

                    b.Navigation("PreferredFloor");

                    b.Navigation("PreferredOffice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Desk", b =>
                {
                    b.Navigation("DeskRecommendations");

                    b.Navigation("DeskSchedules");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Floor", b =>
                {
                    b.Navigation("Desks");

                    b.Navigation("MeetingRooms");

                    b.Navigation("OfficeRooms");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Office", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.OfficeSetting", b =>
                {
                    b.Navigation("Offices");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.Organization", b =>
                {
                    b.Navigation("Offices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Seatgenie.Api.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("DeskRecommendations");

                    b.Navigation("DeskSchedules");

                    b.Navigation("OnboardingSelection");

                    b.Navigation("Sessions");

                    b.Navigation("UserPreference");
                });
#pragma warning restore 612, 618
        }
    }
}
